In [1]:
# Imports 
import csv
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ML_HW_Data_FisherIris.csv to ML_HW_Data_FisherIris (2).csv


In [3]:
# 1. Read in the CSV file “FisherIris_MDL.csv” into a matrix named as “Iris”.
csvf = csv.reader(open('ML_HW_Data_FisherIris.csv', 'r'))
Iris = np.matrix([list(map(int,x)) for x in csvf])
type(Iris)
Iris[0:11,]

matrix([[  2,  14,  33,  50,   0],
        [ 24,  56,  31,  67,   1],
        [ 23,  51,  31,  69,   1],
        [  2,  10,  36,  46,   0],
        [ 20,  52,  30,  65,   1],
        [ 19,  51,  27,  58,   1],
        [ 13,  45,  28,  57,   2],
        [ 16,  47,  33,  63,   2],
        [ 17,  45,  25,  49,   1],
        [ 14,  47,  32,  70,   2],
        [  2,  16,  31,  48, -10]])

In [4]:
# 2. Display the number of row and number of columns of the matrix “Iris”.

print('Row Count, Column Count: ' + str(Iris.shape))


Row Count, Column Count: (150, 5)


In [5]:
# 3. Display all the row numbers that have the 5th column less than 0.

print(np.where(Iris[:,4] < 0)[0])


[ 10  23  58  89 108 136]


In [6]:
# 4. Remove the rows with the 5th column less than 0 from the “Iris” matrix.

Iris = np.delete(Iris,np.where(Iris[:,4] < 0)[0],0)


In [7]:
# 5. Display the number of row and number of columns of the “Iris” matrix again.

print('Row Count, Column Count: ' + str(Iris.shape))


Row Count, Column Count: (144, 5)


In [8]:
# 6. Copy the first 4 columns in the new “Iris” matrix into a new matrix “X”.

X = Iris[:,:4]


In [9]:
# 7. Copy the 5th columns in the new “Iris” matrix into a new variable (or matrix) “Y”.

Y = Iris[:,4]


In [10]:
# 8. Display the maximum value and the minimum value of each column in “X”.

print(np.min(X, axis=0), np.max(X, axis=0))


[[ 1 10 20 43]] [[25 69 44 79]]


In [11]:
# 9. Display the number of elements in the third column of the matrix “X” greater than 36.

idx = np.argwhere(X[:,2] > 36)
print('idx')
print(idx)
print(len(X[idx[:,0]]), len(idx))
print(len(np.argwhere(X[:,2] > 36)))

idx
[[ 16   0]
 [ 19   0]
 [ 27   0]
 [ 44   0]
 [ 46   0]
 [ 73   0]
 [ 77   0]
 [ 85   0]
 [ 87   0]
 [ 92   0]
 [102   0]
 [107   0]
 [114   0]
 [118   0]
 [143   0]]
15 15
15
